site_name: "Polyphonic Polymer Bundle"
repo_url: "https://github.com/headzoo/polymer-bundle"
site_author: "Sean Hickey"
copyright: "2015, Sean Hickey"
markdown_extensions: [fenced_code]
theme: "readthedocs"
docs_dir: Resources/doc

pages:
- ["index.md", "Home"]
- ["installing.md","User Guide", "Installing"]
- ["configuration.md","User Guide", "Configuration"]
- ["custom.md","User Guide", "Creating Custom Elements"]
- ["importing.md","User Guide", "Importing Elements"]
- ["deploy.md","User Guide", "Deploying Your App"]
- ["about/credits.md", "About", "Credits"]
- ["about/license.md", "About", "License"]